name: Client Deploy

on:
  push:
    branches:
      - 'main'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run Test ViTest
        run: npm run test

      - name: Build Docker image (Client)
        run: |
          docker build -t dashflow-client:latest .
          docker save dashflow-client:latest | gzip > dashflow-client.tar.gz

      - name: Transfer Docker image via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.MANOLITO_VM_IP }}
          username: ${{ secrets.MANOLITO_VM_USR }}
          password: ${{ secrets.MANOLITO_VM_PSW }}
          source: "dashflow-client.tar.gz"
          target: "/opt/dashflow-client/"