name: Vue.js Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    - name: Run Test ViTest
      run: npm run test

    - name: Deploy to ManoLitoVM
      uses: appleboy/scp-action@master
      with:
        host: 191.232.189.186
        username: manolito
        password: ManolitoFateco@404!6793
        source: "dist/*"
        target: "/opt/tomcat/webapps/web-client"