name: Vue.js Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '[develop]'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
    
    - name: Run Test ViTest
      run: npm run test

    - name: Deploy to ManoLitoVM Homolog
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.MANOLITO_VM_IP }}
        username: ${{ secrets.MANOLITO_VM_USR }}
        password: ${{ secrets.MANOLITO_VM_PSR }}
        source: "dist/*"
        target: "/opt/tomcat/webapps/web-homolog/"
        strip_components: 1
      